import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SiteHeader } from "@/components/nav-menu/header-nav";
import Head from 'next/head';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta httpEquiv="X-UA-Compatible" content="ie=edge" />
        {/* set icon */}
        <link rel="icon" href="/favicon.ico" />
        <title>WitchCraft Player</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SiteHeader />
        {children}
        <footer className="bg-gray-900 text-white py-8">
          <div className="container mx-auto grid grid-cols-1 md:grid-cols-2 gap-8">

            <div>
              <h3 className="text-xl font-semibold mb-4">Contact Us</h3>
              <p className="mb-2">Have questions or need assistance? Reach out to us:</p>
              <ul>
                <li>Email: <a href="mailto:support@tcgmarketplace.com" className="text-blue-400">support@tcgmarketplace.com</a></li>
                <li>Phone: <a href="tel:+1234567890" className="text-blue-400">+1 234 567 890</a></li>
              </ul>
            </div>

            <div>
              <h3 className="text-xl font-semibold mb-4">Rules of Use</h3>
              <ul className="list-disc list-inside">
                <li>All users must comply with local laws and regulations.</li>
                <li>Only authentic trading cards may be listed for sale.</li>
                <li>Fraudulent activities will result in account suspension or termination.</li>
                <li>Users are responsible for accurate card descriptions and images.</li>
                <li>Transactions are conducted at the buyer's and seller's risk.</li>
              </ul>
              <p className="mt-4">For more details, see our <a href="/terms-and-conditions" className="text-blue-400 underline">Terms and Conditions</a>.</p>
            </div>
          </div>
          <div className="text-center mt-8 text-sm">
            &copy; 2025 TCG Marketplace. All rights reserved.
          </div>
        </footer>
      </body>
    </html>
  );
}
